In [1]:
import pandas as pd
import numpy as np

In [2]:
data_mat = pd.read_csv('student-mat.csv', sep=';')
data_port = pd.read_csv('student-por.csv', sep=';')
final_df = pd.read_csv('df_final_port_mat.csv')

### Checking Failure column for Mats in final dataset

In [3]:
count = pd.unique(data_mat['failures'])
count

array([0, 3, 2, 1], dtype=int64)

In [4]:
data_mat['failures'].value_counts()

0    312
1     50
2     17
3     16
Name: failures, dtype: int64

In [5]:
count = pd.unique(final_df['failures_mat'])
count

array([ 2.,  1.,  0.,  3., nan])

In [6]:
final_df['failures_mat'].value_counts()

0.0    312
1.0     50
2.0     17
3.0     16
Name: failures_mat, dtype: int64

#### Error Resolved

### Checking Failure column for por in final dataset

In [7]:
count = pd.unique(data_port['failures'])
count

array([0, 3, 1, 2], dtype=int64)

In [8]:
data_port['failures'].value_counts()

0    549
1     70
2     16
3     14
Name: failures, dtype: int64

In [9]:
final_df['failures_por'].value_counts()

0.0    549
1.0     70
2.0     16
3.0     14
Name: failures_por, dtype: int64

#### No review needed

### Checking for absences in both datasets

In [10]:
count = pd.unique(data_mat['absences'])
count.sort()
count

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 30, 38, 40, 54, 56, 75],
      dtype=int64)

In [11]:
count = pd.unique(final_df['absences_mat'])
count.sort()
count

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 28., 30., 38., 40., 54., 56., 75., nan])

In [12]:
data_mat['absences'].value_counts()

0     115
2      65
4      53
6      31
8      22
10     17
14     12
12     12
3       8
16      7
7       7
5       5
18      5
20      4
11      3
9       3
13      3
15      3
22      3
1       3
38      1
30      1
40      1
23      1
19      1
28      1
75      1
21      1
24      1
56      1
26      1
54      1
25      1
17      1
Name: absences, dtype: int64

In [13]:
final_df['absences_mat'].value_counts()

0.0     115
2.0      65
4.0      53
6.0      31
8.0      22
10.0     17
12.0     12
14.0     12
3.0       8
7.0       7
16.0      7
5.0       5
18.0      5
20.0      4
22.0      3
15.0      3
9.0       3
11.0      3
1.0       3
13.0      3
23.0      1
19.0      1
30.0      1
75.0      1
21.0      1
24.0      1
28.0      1
56.0      1
26.0      1
54.0      1
25.0      1
38.0      1
40.0      1
17.0      1
Name: absences_mat, dtype: int64

#### No review needed

In [14]:
count = pd.unique(data_port['absences'])
count.sort()
count

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       18, 21, 22, 24, 26, 30, 32], dtype=int64)

In [15]:
count = pd.unique(final_df['absences_por'])
count.sort()
count

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 18., 21., 22., 24., 26., 30., 32., nan])

In [16]:
data_port['absences'].value_counts()

0     244
2     110
4      93
6      49
8      42
10     21
1      12
12     12
5      12
16     10
14      8
9       7
3       7
11      5
18      3
7       3
21      2
15      2
22      2
30      1
26      1
24      1
13      1
32      1
Name: absences, dtype: int64

In [17]:
final_df['absences_por'].value_counts()

0.0     244
2.0     110
4.0      93
6.0      49
8.0      42
10.0     21
12.0     12
1.0      12
5.0      12
16.0     10
14.0      8
3.0       7
9.0       7
11.0      5
7.0       3
18.0      3
21.0      2
22.0      2
15.0      2
26.0      1
13.0      1
24.0      1
32.0      1
30.0      1
Name: absences_por, dtype: int64

#### No review needed

### Checking for paid

In [18]:
data_mat['paid'].value_counts()

no     214
yes    181
Name: paid, dtype: int64

In [19]:
final_df['paid_mat'].value_counts()

no     214
yes    181
Name: paid_mat, dtype: int64

#### Error resolved

In [20]:
data_port['paid'].value_counts()

no     610
yes     39
Name: paid, dtype: int64

In [21]:
final_df['paid_por'].value_counts()

no     610
yes     39
Name: paid_por, dtype: int64

#### No review needed

### Checking G1 column

In [22]:
data_mat['G1'].value_counts()

10    51
8     41
11    39
7     37
12    35
13    33
9     31
14    30
15    24
6     24
16    22
18     8
17     8
5      7
19     3
4      1
3      1
Name: G1, dtype: int64

In [23]:
final_df['G1_mat'].value_counts()

10.0    51
8.0     41
11.0    39
7.0     37
12.0    35
13.0    33
9.0     31
14.0    30
15.0    24
6.0     24
16.0    22
17.0     8
18.0     8
5.0      7
19.0     3
4.0      1
3.0      1
Name: G1_mat, dtype: int64

#### No review needed

In [24]:
data_port['G1'].value_counts()#### No review needed

10    95
11    91
12    82
13    72
14    71
9     65
8     42
15    35
7     33
16    22
17    16
6      9
18     7
5      5
4      2
0      1
19     1
Name: G1, dtype: int64

In [25]:
final_df['G1_por'].value_counts()

10.0    95
11.0    91
12.0    82
13.0    72
14.0    71
9.0     65
8.0     42
15.0    35
7.0     33
16.0    22
17.0    16
6.0      9
18.0     7
5.0      5
4.0      2
0.0      1
19.0     1
Name: G1_por, dtype: int64

#### No review needed

### Checking for G2

In [26]:
data_mat['G2'].value_counts()

9     50
10    46
12    41
13    37
11    35
15    34
8     32
14    23
7     21
5     15
6     14
16    13
0     13
18    12
17     5
19     3
4      1
Name: G2, dtype: int64

In [27]:
final_df['G2_mat'].value_counts()

9.0     50
10.0    46
12.0    41
13.0    37
11.0    35
15.0    34
8.0     32
14.0    23
7.0     21
5.0     15
6.0     14
16.0    13
0.0     13
18.0    12
17.0     5
19.0     3
4.0      1
Name: G2_mat, dtype: int64

#### No review needed

In [28]:
data_port['G2'].value_counts()

11    103
12     86
10     83
13     80
9      72
14     54
8      40
15     38
16     25
17     20
7      16
18     14
6       7
0       7
5       3
19      1
Name: G2, dtype: int64

In [29]:
final_df['G2_por'].value_counts()

11.0    103
12.0     86
10.0     83
13.0     80
9.0      72
14.0     54
8.0      40
15.0     38
16.0     25
17.0     20
7.0      16
18.0     14
6.0       7
0.0       7
5.0       3
19.0      1
Name: G2_por, dtype: int64

#### No review needed

### Checking for G3

In [30]:
data_mat['G3'].value_counts()

10    56
11    47
0     38
15    33
8     32
13    31
12    31
9     28
14    27
16    16
6     15
18    12
7      9
5      7
17     6
19     5
20     1
4      1
Name: G3, dtype: int64

In [31]:
final_df['G3_mat'].value_counts()

10.0    56
11.0    47
0.0     38
15.0    33
8.0     32
12.0    31
13.0    31
9.0     28
14.0    27
16.0    16
6.0     15
18.0    12
7.0      9
5.0      7
17.0     6
19.0     5
20.0     1
4.0      1
Name: G3_mat, dtype: int64

#### No review needed

In [32]:
data_port['G3'].value_counts()

11    104
10     97
13     82
12     72
14     63
15     49
16     36
9      35
8      35
17     29
18     15
0      15
7      10
6       3
19      2
1       1
5       1
Name: G3, dtype: int64

In [33]:
final_df['G3_por'].value_counts()

11.0    104
10.0     97
13.0     82
12.0     72
14.0     63
15.0     49
16.0     36
9.0      35
8.0      35
17.0     29
18.0     15
0.0      15
7.0      10
6.0       3
19.0      2
1.0       1
5.0       1
Name: G3_por, dtype: int64

#### No review needed

### Inference  
##### Errors about paid_math and failure_math are resolved